### ISSUE TITLE
Add Ubuntu or non-osx support 

### ISSUE THREAD

**Issue by kevinkhill** [auchenberg/dotdev#3]
Do you have any plans on expanding this solution to Ubuntu or non-osx in general?

**Comment by auchenberg** [comment]
This was a quick-hack a late night, a long time ago, so no. But if you know what would be needed, and want to spend the time, I'm happy to accept a pull-request :)

**Comment by kevinkhill** [comment]
I know much more about web stacks then networking, but hey, maybe I'll take
a stab at it sometime
